server:
  port: 8083



spring:
  jackson:
    time-zone: UTC
  jpa:
    defer-datasource-initialization: true
    database: mysql
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3303/keycloak?useSSL=false
    username: keycloak
    password: keycloak01*
    driver-class-name: com.mysql.cj.jdbc.Driver

keycloak:
  connectionsJpa:
    url: jdbc:mysql://localhost:3303/keycloak?useSSL=false
    driver: com.mysql.cj.jdbc.Driver
    user: keycloak
    password: keycloak01*
  server:
    contextPath: /auth
    adminUser:
      username: admin
      password: admin
    realmImportFile: keycloak-server.json
logging:
  level:
    org:
      keycloak: DEBUG